"""
pdf_service.py — Server-side PDF generation for 7G House.

Builds a branded A4 PDF (landscape-safe) using Pillow + ImageDraw:
  • Page 1: Cover page with project specs
  • Pages 2…N: One project image per page, full-bleed, with label caption

Supports English and French (lang="en" | "fr").

No browser CORS issues — images are fetched directly by the backend.
"""

import io
import os
import logging
import textwrap
import asyncio
from typing import Optional

import httpx
from PIL import Image, ImageDraw, ImageFont

logger = logging.getLogger(__name__)


def _t(label: str, lang: str = "en") -> str:
    """Simple inline translation helper for PDF strings."""
    is_fr = lang == "fr"
    translations = {
        "header_title": ("7G HOUSE", "7G HOUSE"),
        "header_subtitle": ("CONSTRUCTION INTELLIGENCE REPORT", "RAPPORT D'INTELLIGENCE DE CONSTRUCTION"),
        "footer_tagline": ("7G House Cameroon — Architectural Intelligence", "7G House Cameroun — Intelligence Architecturale"),
        "page": ("Page", "Page"),
        "project_report": ("PROJECT REPORT", "RAPPORT DE PROJET"),
        "floor_plan_title": ("Floor Plan — {bedrooms}-Bedroom Project", "Plan d'Étage — Projet {bedrooms} Chambres"),
        "house_design_title": ("{style} House Design", "Design Maison {style}"),
        "prepared_for": ("Prepared for: {client}", "Préparé pour : {client}"),
        "region": ("Region", "Région"),
        "division": ("Division", "Département"),
        "bedrooms": ("Bedrooms", "Chambres"),
        "bathrooms": ("Bathrooms", "Salles de bain"),
        "gross_area": ("Gross Area", "Surface Brute"),
        "kitchen": ("Kitchen", "Cuisine"),
        "extras": ("Extras", "Pièces Additionnelles"),
        "style": ("Style", "Style"),
        "roof": ("Roof", "Toiture"),
        "foundation": ("Foundation", "Fondation"),
        "key_rooms": ("Key Rooms", "Pièces Clés"),
        "outdoor": ("Outdoor", "Extérieurs"),
        "desc_blurb": (
            "This document contains the architectural visualisation report for the "
            "specified property, including floor plans, elevations, exterior renders, "
            "cross-sections, and structural views generated by the 7G House AI platform.",
            "Ce document contient le rapport de visualisation architecturale pour la "
            "propriété spécifiée, y compris les plans d'étage, les élévations, les rendus "
            "extérieurs, les coupes et les vues structurelles générées par la plateforme IA 7G House.",
        ),
        "pdf_title": ("7G House Construction Intelligence Report", "Rapport d'Intelligence de Construction 7G House"),
        "pdf_subject": ("Architectural Visualisation Report", "Rapport de Visualisation Architecturale"),
        "view_label": ("View", "Vue"),
        "cost_estimate_title": ("Estimated Project Budget", "Budget Projet Estimé"),
        "cost_material_hub": ("Material Source", "Source des Matériaux"),
        "cost_hub_distance": ("from building site", "du site de construction"),
        "cost_component": ("Component", "Composant"),
        "cost_ratio": ("Ratio", "Ratio"),
        "cost_fcfa": ("FCFA", "FCFA"),
        "cost_materials": ("Materials", "Matériaux"),
        "cost_transport": ("Transport", "Transport"),
        "cost_labour": ("Labour", "Main-d'œuvre"),
        "cost_terrain": ("Terrain Adj.", "Ajust. Terrain"),
        "cost_contingency": ("Contingency (10%)", "Imprévus (10%)"),
        "cost_subtotal": ("Subtotal", "Sous-total"),
        "cost_grand_total": ("Grand Total", "Total Général"),
        "cost_usd_equiv": ("USD Equivalent", "Équivalent USD"),
        "cost_per_m2": ("Cost per m²", "Coût au m²"),
        "cost_notes": ("Estimate Notes", "Notes d'Estimation"),
        "rooms_title": ("Room Dimensions", "Dimensions des Pièces"),
        "rooms_total": ("Total Rooms", "Total Pièces"),
        "rooms_total_area": ("Total Area", "Surface Totale"),
        "rooms_avg_size": ("Avg Size", "Taille Moy"),
        "rooms_col_room": ("Room", "Pièce"),
        "rooms_col_code": ("Code", "Code"),
        "rooms_col_width": ("Width (m)", "Larg (m)"),
        "rooms_col_height": ("Height (m)", "Haut (m)"),
        "rooms_col_area": ("Area (m²)", "Surface (m²)"),
        "rooms_empty": ("No room measurements available.", "Aucune mesure de pièce disponible."),
    }
    val = translations.get(label, (label, label))
    return val[1] if is_fr else val[0]

# ── A4 at 150 dpi ─────────────────────────────────────────────────────────────
A4_W = 1240
A4_H = 1754

# ── Colour palette ─────────────────────────────────────────────────────────────
CLR_PRIMARY = (26, 82, 118)       # #1a5276
CLR_ACCENT  = (46, 134, 193)      # #2e86c1
CLR_BG      = (248, 249, 250)     # #f8f9fa
CLR_WHITE   = (255, 255, 255)
CLR_DARK    = (26, 26, 46)        # #1a1a2e
CLR_MUTED   = (102, 102, 102)     # #666666
CLR_BORDER  = (208, 208, 208)     # #d0d0d0

# ── Font paths ─────────────────────────────────────────────────────────────────
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
_FONT_REGULAR = os.path.join(_BACKEND_DIR, "fonts", "NotoSans-Variable.ttf")
_FONT_BOLD    = _FONT_REGULAR   # variable font covers bold weights


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    try:
        if bold:
            return ImageFont.truetype(_FONT_BOLD, size)
        return ImageFont.truetype(_FONT_REGULAR, size)
    except Exception:
        return ImageFont.load_default()


def _draw_watermark(page: Image.Image, w: int, h: int) -> None:
    """Tile a faint diagonal '7G HOUSE' watermark across the page."""
    try:
        wm_font = _font(120, bold=True)
    except Exception:
        return
    text = "7G HOUSE"
    step_x, step_y = 400, 350
    for row in range(-1, h // step_y + 2):
        for col in range(-1, w // step_x + 2):
            x = col * step_x + (row % 2) * (step_x // 2) - 60
            y = row * step_y - 40
            try:
                tmp = Image.new("RGBA", (500, 160), (0, 0, 0, 0))
                tmp_d = ImageDraw.Draw(tmp)
                tmp_d.text((10, 10), text, font=wm_font, fill=(80, 80, 80, 18))
                tmp = tmp.rotate(35, expand=True)
                page.paste(tmp, (x, y), tmp)
            except Exception:
                pass


def _draw_header(draw: ImageDraw.ImageDraw, w: int, lang: str = "en") -> None:
    """Top dark header band with logo text + report title."""
    draw.rectangle([0, 0, w, 90], fill=CLR_PRIMARY)
    draw.text((36, 18), _t("header_title", lang), font=_font(32, bold=True), fill=CLR_WHITE)
    draw.text((36, 56), _t("header_subtitle", lang), font=_font(14), fill=(180, 210, 240))
    # Right-side accent bar
    draw.rectangle([w - 8, 0, w, 90], fill=CLR_ACCENT)


def _draw_footer(draw: ImageDraw.ImageDraw, w: int, h: int, page_num: int, lang: str = "en") -> None:
    """Bottom footer with border, tagline and page number."""
    fy = h - 60
    draw.line([(36, fy), (w - 36, fy)], fill=CLR_BORDER, width=1)
    draw.text(
        (36, fy + 10),
        _t("footer_tagline", lang),
        font=_font(14),
        fill=CLR_MUTED,
    )
    pn = f"{_t('page', lang)} {page_num}"
    draw.text((w - 120, fy + 10), pn, font=_font(14), fill=CLR_MUTED)


def _build_cover_page(generation_data: dict, page_num: int = 1, lang: str = "en") -> Image.Image:
    """Build the cover/spec page."""
    img = Image.new("RGB", (A4_W, A4_H), CLR_BG)
    draw = ImageDraw.Draw(img)

    # Watermark
    _draw_watermark(img, A4_W, A4_H)
    # Header
    _draw_header(draw, A4_W, lang)

    # ── Title block ───────────────────────────────────────────────────────────
    ty = 130
    gen_type = generation_data.get("generation_type", "house_plan")
    spec = generation_data.get("floor_plan_spec") or {}

    # Main title
    if gen_type == "floor_plan":
        bedrooms = spec.get("num_bedrooms", 0)
        title = _t("floor_plan_title", lang).format(bedrooms=bedrooms)
    else:
        style = generation_data.get("house_style") or "Residential"
        title = _t("house_design_title", lang).format(style=style)

    draw.text((A4_W // 2, ty), _t("project_report", lang), font=_font(48, bold=True),
              fill=CLR_PRIMARY, anchor="mt")

    # Accent divider
    div_w = 100
    draw.rectangle([(A4_W // 2 - div_w // 2, ty + 72),
                    (A4_W // 2 + div_w // 2, ty + 78)], fill=CLR_ACCENT)

    draw.text((A4_W // 2, ty + 96), title, font=_font(28),
              fill=CLR_DARK, anchor="mt")

    # Client name if present
    client = generation_data.get("client_name")
    if client:
        draw.text((A4_W // 2, ty + 140), _t("prepared_for", lang).format(client=client),
                  font=_font(20), fill=CLR_MUTED, anchor="mt")

    # ── Spec table ────────────────────────────────────────────────────────────
    table_top = ty + 200
    draw.rectangle([80, table_top, A4_W - 80, table_top + 2], fill=CLR_BORDER)

    rows: list[tuple[str, str]] = []
    _labels = {
        "region": _t("region", lang),
        "division": _t("division", lang),
        "bedrooms": _t("bedrooms", lang),
        "bathrooms": _t("bathrooms", lang),
        "gross_area": _t("gross_area", lang),
        "kitchen": _t("kitchen", lang),
        "extras": _t("extras", lang),
        "style": _t("style", lang),
        "roof": _t("roof", lang),
        "foundation": _t("foundation", lang),
        "key_rooms": _t("key_rooms", lang),
        "outdoor": _t("outdoor", lang),
    }

    if gen_type == "floor_plan":
        rows = [
            (_labels["region"],   spec.get("region", "—")),
            (_labels["division"], spec.get("division", "—")),
            (_labels["bedrooms"], str(spec.get("num_bedrooms", "—"))),
            (_labels["bathrooms"], str(spec.get("num_bathrooms", "—"))),
            (_labels["gross_area"], f"{spec.get('gross_area', '—')} m²"),
            (_labels["kitchen"],  str(spec.get("kitchen_type", "—")).capitalize()),
        ]
        if extras := spec.get("extras"):
            rows.append((_labels["extras"], ", ".join(extras)))
    else:
        rows = [
            (_labels["style"],      generation_data.get("house_style", "—")),
            (_labels["region"],     generation_data.get("region", "—")),
            (_labels["division"],   generation_data.get("division", "—")),
            (_labels["bedrooms"],   str(generation_data.get("num_bedrooms", "—"))),
            (_labels["bathrooms"],  str(generation_data.get("num_bathrooms", "—"))),
            (_labels["gross_area"], f"{generation_data.get('gross_area', '—')} m²"),
            (_labels["roof"],       generation_data.get("roof_type", "—")),
            (_labels["foundation"], generation_data.get("foundation", "—")),
        ]
        if ks := generation_data.get("key_rooms"):
            rows.append((_labels["key_rooms"], ", ".join(ks)))
        if os_ := generation_data.get("outdoor_spaces"):
            rows.append((_labels["outdoor"], ", ".join(os_)))

    row_h = 58
    for i, (label, value) in enumerate(rows):
        ry = table_top + 16 + i * row_h
        bg_col = CLR_WHITE if i % 2 == 0 else CLR_BG
        draw.rectangle([80, ry, A4_W - 80, ry + row_h - 4], fill=bg_col)
        draw.text((100, ry + 10), label.upper(), font=_font(14, bold=True),
                  fill=CLR_MUTED)
        # Wrap long values
        wrapped = textwrap.fill(value, width=50)
        draw.text((480, ry + 10), wrapped, font=_font(18, bold=True),
                  fill=CLR_PRIMARY)

    # ── Description blurb ─────────────────────────────────────────────────────
    desc_y = table_top + 30 + len(rows) * row_h + 20
    desc = _t("desc_blurb", lang)
    for i, line in enumerate(textwrap.wrap(desc, width=90)):
        draw.text((A4_W // 2, desc_y + i * 28), line,
                  font=_font(16), fill=CLR_MUTED, anchor="mt")

    # Footer
    _draw_footer(draw, A4_W, A4_H, page_num, lang)

    return img


def _build_cost_estimate_page(cost: dict, page_num: int = 2, lang: str = "en") -> Optional[Image.Image]:
    try:
        img = Image.new("RGB", (A4_W, A4_H), CLR_BG)
        draw = ImageDraw.Draw(img)

        _draw_watermark(img, A4_W, A4_H)
        _draw_header(draw, A4_W, lang)

        hub_name = cost.get("hub_name", "—")
        distance_km = cost.get("distance_km", 0)
        grand_total = cost.get("grand_total_fcfa", 0)
        grand_total_usd = cost.get("grand_total_usd", 0)
        base_per_m2 = cost.get("base_cost_per_m2", 0)
        breakdown = cost.get("breakdown", [])
        notes = cost.get("notes", [])

        # Title
        draw.text((A4_W // 2, 130), _t("cost_estimate_title", lang),
                  font=_font(36, bold=True), fill=CLR_PRIMARY, anchor="mt")

        # Hub info
        hub_line = f"{hub_name}"
        if distance_km > 0:
            hub_line += f" — {distance_km:.0f} km {_t('cost_hub_distance', lang)}"
        draw.text((A4_W // 2, 180), hub_line,
                  font=_font(18), fill=CLR_MUTED, anchor="mt")

        # Divider
        draw.rectangle([80, 210, A4_W - 80, 214], fill=CLR_BORDER)

        # Breakdown table
        table_top = 240
        row_h = 50
        col_label_x = 100
        col_ratio_x = 520
        col_amount_x = 700

        # Header row
        draw.rectangle([80, table_top, A4_W - 80, table_top + row_h - 4], fill=CLR_PRIMARY)
        draw.text((col_label_x, table_top + 12), _t("cost_component", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)
        draw.text((col_ratio_x, table_top + 12), _t("cost_ratio", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)
        draw.text((col_amount_x, table_top + 12), _t("cost_fcfa", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)

        labels_map = {
            "Materials": _t("cost_materials", lang),
            "Transport": _t("cost_transport", lang),
            "Labour": _t("cost_labour", lang),
            "Terrain Adjustment": _t("cost_terrain", lang),
            "Contingency": _t("cost_contingency", lang),
        }

        for i, item in enumerate(breakdown):
            ry = table_top + row_h + i * row_h
            bg = CLR_WHITE if i % 2 == 0 else CLR_BG
            draw.rectangle([80, ry, A4_W - 80, ry + row_h - 4], fill=bg)

            label = labels_map.get(item["label"], item["label"])
            draw.text((col_label_x, ry + 12), label,
                      font=_font(16, bold=True), fill=CLR_DARK)
            draw.text((col_ratio_x, ry + 12), f'{item["pct"]}%',
                      font=_font(14), fill=CLR_MUTED)
            draw.text((col_amount_x, ry + 12), f'{item["amount"]:,}',
                      font=_font(16, bold=True), fill=CLR_PRIMARY)

        # Grand total row
        total_y = table_top + row_h + len(breakdown) * row_h + 8
        draw.rectangle([80, total_y, A4_W - 80, total_y + row_h], fill=CLR_PRIMARY)
        draw.text((col_label_x, total_y + 12), _t("cost_grand_total", lang),
                  font=_font(18, bold=True), fill=CLR_WHITE)
        draw.text((col_amount_x, total_y + 12), f'{grand_total:,} FCFA',
                  font=_font(18, bold=True), fill=CLR_WHITE)

        # USD equivalent & per m²
        info_y = total_y + row_h + 16
        draw.text((A4_W // 2, info_y),
                  f'{_t("cost_usd_equiv", lang)}: ~{grand_total_usd:,} USD  |  {_t("cost_per_m2", lang)}: {base_per_m2:,} FCFA/m²',
                  font=_font(16), fill=CLR_MUTED, anchor="mt")

        # Notes
        if notes:
            notes_y = info_y + 50
            draw.text((A4_W // 2, notes_y), _t("cost_notes", lang),
                      font=_font(16, bold=True), fill=CLR_DARK, anchor="mt")
            for j, note in enumerate(notes):
                draw.text((A4_W // 2, notes_y + 30 + j * 26), f"• {note}",
                          font=_font(14), fill=CLR_MUTED, anchor="mt")

        _draw_footer(draw, A4_W, A4_H, page_num, lang)
        return img
    except Exception as e:
        logger.warning(f"pdf_service: cost estimate page failed: {e}")
        return None


def _build_room_dimensions_page(rooms: list[dict], page_num: int = 3, lang: str = "en") -> Optional[Image.Image]:
    try:
        img = Image.new("RGB", (A4_W, A4_H), CLR_BG)
        draw = ImageDraw.Draw(img)

        _draw_watermark(img, A4_W, A4_H)
        _draw_header(draw, A4_W, lang)

        # Title
        draw.text((A4_W // 2, 130), _t("rooms_title", lang),
                  font=_font(36, bold=True), fill=CLR_PRIMARY, anchor="mt")

        # Summary line
        total_area = sum(r.get("area_m2", 0) for r in rooms)
        avg = total_area / len(rooms) if rooms else 0
        summary = f'{len(rooms)} {_t("rooms_total", lang)}  |  {_t("rooms_total_area", lang)}: {total_area:.1f} m²  |  {_t("rooms_avg_size", lang)}: {avg:.1f} m²'
        draw.text((A4_W // 2, 180), summary,
                  font=_font(16), fill=CLR_MUTED, anchor="mt")

        # Divider
        draw.rectangle([80, 215, A4_W - 80, 219], fill=CLR_BORDER)

        # Table
        table_top = 250
        row_h = 48
        col_name_x = 100
        col_code_x = 360
        col_width_x = 530
        col_height_x = 660
        col_area_x = 790

        # Header row
        draw.rectangle([80, table_top, A4_W - 80, table_top + row_h - 4], fill=CLR_PRIMARY)
        draw.text((col_name_x, table_top + 12), _t("rooms_col_room", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)
        draw.text((col_code_x, table_top + 12), _t("rooms_col_code", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)
        draw.text((col_width_x, table_top + 12), _t("rooms_col_width", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)
        draw.text((col_height_x, table_top + 12), _t("rooms_col_height", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)
        draw.text((col_area_x, table_top + 12), _t("rooms_col_area", lang).upper(),
                  font=_font(14, bold=True), fill=CLR_WHITE)

        for i, room in enumerate(rooms):
            ry = table_top + row_h + i * row_h
            bg = CLR_WHITE if i % 2 == 0 else CLR_BG
            draw.rectangle([80, ry, A4_W - 80, ry + row_h - 4], fill=bg)

            draw.text((col_name_x, ry + 10), room.get("name", ""),
                      font=_font(16, bold=True), fill=CLR_DARK)
            draw.text((col_code_x, ry + 10), str(room.get("code", "")),
                      font=_font(14), fill=CLR_MUTED)
            draw.text((col_width_x, ry + 10), f'{room.get("width_m", 0):.1f}',
                      font=_font(16, bold=True), fill=CLR_PRIMARY)
            draw.text((col_height_x, ry + 10), f'{room.get("height_m", 0):.1f}',
                      font=_font(16, bold=True), fill=CLR_PRIMARY)
            draw.text((col_area_x, ry + 10), f'{room.get("area_m2", 0):.1f}',
                      font=_font(16, bold=True), fill=CLR_PRIMARY)

        # Total row
        total_y = table_top + row_h + len(rooms) * row_h + 8
        draw.rectangle([80, total_y, A4_W - 80, total_y + row_h], fill=CLR_PRIMARY)
        draw.text((col_name_x, total_y + 10), _t("rooms_total", lang),
                  font=_font(18, bold=True), fill=CLR_WHITE)
        draw.text((col_area_x, total_y + 10), f'{total_area:.1f}',
                  font=_font(18, bold=True), fill=CLR_WHITE)

        _draw_footer(draw, A4_W, A4_H, page_num, lang)
        return img
    except Exception as e:
        logger.warning(f"pdf_service: room dimensions page failed: {e}")
        return None


def _fit_image_to_page(src: Image.Image) -> Image.Image:
    """Scale src to fit within the A4 image area (keeping aspect ratio)."""
    area_w = A4_W - 80
    area_h = A4_H - 200   # leave room for header (90) + footer (60) + caption
    ratio = min(area_w / src.width, area_h / src.height)
    new_w = int(src.width * ratio)
    new_h = int(src.height * ratio)
    return src.resize((new_w, new_h), Image.LANCZOS)


def _build_image_page(
    img_data: bytes,
    label: str,
    page_num: int,
    lang: str = "en",
) -> Optional[Image.Image]:
    """Build a single A4 page containing one project image + label."""
    try:
        src = Image.open(io.BytesIO(img_data)).convert("RGB")
    except Exception as e:
        logger.warning(f"pdf_service: cannot open image for page {page_num}: {e}")
        return None

    page = Image.new("RGB", (A4_W, A4_H), CLR_BG)
    draw = ImageDraw.Draw(page)

    _draw_watermark(page, A4_W, A4_H)
    _draw_header(draw, A4_W, lang)

    # Fit and centre the image
    fitted = _fit_image_to_page(src)
    x = (A4_W - fitted.width) // 2
    y = 100 + (A4_H - 200 - fitted.height) // 2
    page.paste(fitted, (x, y))

    # Caption
    if label:
        cap_y = y + fitted.height + 16
        draw.text((A4_W // 2, cap_y), label.upper(),
                  font=_font(18, bold=True), fill=CLR_MUTED, anchor="mt")

    _draw_footer(draw, A4_W, A4_H, page_num, lang)
    return page


async def build_project_pdf(generation_data: dict, lang: str = "en") -> Optional[io.BytesIO]:
    """
    Build a branded multi-page PDF from a generation document.
    Returns a BytesIO buffer with name set to 'Project_Report.pdf',
    or None on failure.
    """
    images: list[dict] = generation_data.get("images", [])
    headers = {"User-Agent": "7G-House-PDF/1.0"}

    pages: list[Image.Image] = []

    # ── Page 1: Cover ─────────────────────────────────────────────────────────
    try:
        cover = _build_cover_page(generation_data, page_num=1, lang=lang)
        pages.append(cover)
    except Exception as e:
        logger.error(f"pdf_service: cover page failed: {e}")

    # ── Page 2: Cost Estimate (if available) ───────────────────────────────────
    page_num = 2
    cost_estimate = generation_data.get("cost_estimate")
    if cost_estimate:
        try:
            ce_page = _build_cost_estimate_page(cost_estimate, page_num=page_num, lang=lang)
            if ce_page:
                pages.append(ce_page)
                page_num += 1
        except Exception as e:
            logger.warning(f"pdf_service: cost estimate page failed: {e}")

    # ── Page 3: Room Dimensions (if available) ─────────────────────────────────
    room_measurements = generation_data.get("room_measurements", [])
    if room_measurements:
        try:
            rd_page = _build_room_dimensions_page(room_measurements, page_num=page_num, lang=lang)
            if rd_page:
                pages.append(rd_page)
                page_num += 1
        except Exception as e:
            logger.warning(f"pdf_service: room dimensions page failed: {e}")

    # ── Pages 4…N+: Project images ─────────────────────────────────────────────
    async with httpx.AsyncClient(headers=headers, timeout=30.0) as client:
        for img_meta in images:
            url = img_meta.get("url", "")
            label = img_meta.get("label", "") or f"{_t('view_label', lang)} {page_num - 1}"
            if not url:
                continue
            try:
                resp = await client.get(url, follow_redirects=True)
                resp.raise_for_status()
                img_bytes = resp.content
            except Exception as e:
                logger.warning(f"pdf_service: failed to download image '{url[:60]}': {e}")
                continue

            page = _build_image_page(img_bytes, label, page_num, lang=lang)
            if page:
                pages.append(page)
                page_num += 1

    if not pages:
        logger.error("pdf_service: no pages generated")
        return None

    # ── Assemble PDF ───────────────────────────────────────────────────────────
    def _assemble_pdf():
        buf = io.BytesIO()
        first = pages[0]
        rest  = pages[1:] if len(pages) > 1 else []
        first.save(
            buf,
            format="PDF",
            save_all=True,
            append_images=rest,
            resolution=150,
            title=_t("pdf_title", lang),
            author="7G House",
            subject=_t("pdf_subject", lang),
        )
        buf.seek(0)
        buf.name = "Project_Report.pdf"
        return buf

    try:
        buf = await asyncio.to_thread(_assemble_pdf)
    except Exception as e:
        logger.error(f"pdf_service: failed to save PDF: {e}")
        return None

    logger.info(
        f"pdf_service: built PDF with {len(pages)} pages "
        f"({len(buf.getvalue())} bytes)"
    )
    return buf


async def upload_pdf_to_storage(pdf_buf: io.BytesIO, generation_id: str) -> Optional[str]:
    """
    Upload the PDF buffer to Firebase Storage and return the public URL.
    Uses the same bucket as storage_service.
    """
    from app.db.firebase import bucket
    import uuid

    if bucket is None:
        logger.error("pdf_service: Firebase Storage bucket not initialised")
        return None

    try:
        blob_path = f"telegram_pdfs/{generation_id}/{uuid.uuid4().hex}.pdf"
        blob = bucket.blob(blob_path)
        pdf_buf.seek(0)
        blob.upload_from_file(pdf_buf, content_type="application/pdf")
        blob.make_public()
        url = blob.public_url
        logger.info(f"pdf_service: uploaded PDF → {url}")
        return url
    except Exception as e:
        logger.error(f"pdf_service: upload failed: {e}")
        return None


async def delete_pdf_from_storage(pdf_url: str) -> bool:
    """Delete a PDF file from Firebase Storage given its public URL."""
    from app.db.firebase import bucket

    if bucket is None:
        logger.error("pdf_service: Firebase Storage bucket not initialised")
        return False

    if not pdf_url:
        return False

    try:
        from urllib.parse import urlparse
        parsed = urlparse(pdf_url)
        blob_path = parsed.path.lstrip("/")
        if blob_path.startswith(f"{bucket.name}/"):
            blob_path = blob_path[len(bucket.name) + 1:]
        blob = bucket.blob(blob_path)
        if blob.exists():
            blob.delete()
            logger.info(f"pdf_service: deleted PDF from storage → {blob_path}")
            return True
        else:
            logger.warning(f"pdf_service: PDF blob not found → {blob_path}")
            return False
    except Exception as e:
        logger.error(f"pdf_service: delete failed: {e}")
        return False
